(function () {
  window.ENABLE_ART_PACK_01 = window.ENABLE_ART_PACK_01 !== false;
  window.ART_ASSETS = window.ART_ASSETS || {};

  window.ART_ASSETS.props = {
    leafBroom: "assets/props/leaf_broom.png",
    flowerSeeds: "assets/props/flower_seeds.png",
    pencil: "assets/props/pencil.png",
    bell: "assets/props/bell.png",
    leafLamp: "assets/props/leaf_lamp.png",
    hangingLantern: "assets/props/hanging_lantern.png",
    map: "assets/props/map.png",
    treasureChest: "assets/props/treasure_chest.png",
    magicPencil: "assets/props/magic_pencil.png",
    flowerBulbLamp: "assets/props/flower_bulb_lamp.png",
    flowerBed: "assets/props/flower_bed.png",
    treeStringLights: "assets/props/tree_string_lights.png",
    antLeaf: "assets/props/ant_leaf.png",
    antStick: "assets/props/ant_stick.png",
    antFlower: "assets/props/ant_flower.png",
    puddle: "assets/props/puddle.png",
    lampPost: "assets/props/lamp_post.png",
    lantern: "assets/props/lantern.png",
    schoolSign: "assets/props/school_sign.png",
    bouncingMushroom: "assets/props/bouncing_mushroom.png",
    finishFlag: "assets/props/finish_flag.png",
    moonPillar: "assets/props/moon_pillar.png",
    bubbleSlide: "assets/props/bubble_slide.png",
    pearlSwitch: "assets/props/pearl_switch.png",
    moonLamp: "assets/items/moon_lamp.png",
    boatPaddle: "assets/items/boat_paddle.png",
    moonKey: "assets/items/moon_key.png",
    shellBadge: "assets/items/shell_badge.png",
    bubbleDivingHelmet: "assets/items/bubble_diving_helmet.png",
    bubbleStone: "assets/items/bubble_stone.png",
    pearlOrb: "assets/items/pearl_orb.png",
    coralKey: "assets/items/coral_key.png",
    spiralShell: "assets/items/spiral_shell.png",
    seaweedScissors: "assets/items/seaweed_scissors.png",
    jellyfishCore: "assets/items/jellyfish_core.png",
    aquaGem: "assets/items/aqua_gem.png",
    deepRune: "assets/items/deep_rune.png",
    moonPearl: "assets/items/moon_pearl.png",
    pearlCrown: "assets/items/pearl_crown.png",
    redApple: "assets/items/red_apple.png?v=apple-game-ready-v2-20260713",
    greenApple: "assets/items/green_apple.png?v=apple-game-ready-v2-20260713",
    goldenApple: "assets/items/golden_apple.png?v=apple-game-ready-v2-20260713",
    appleBasket: "assets/items/apple_basket_alt.png?v=apple-game-ready-v2-20260713",
    giftAppleBasket: "assets/items/gift_apple_basket.png?v=apple-game-ready-v2-20260713",
    redAppleBasket: "assets/items/red_apple_basket.png?v=apple-game-ready-v2-20260713",
    greenAppleBasket: "assets/items/green_apple_basket.png?v=apple-game-ready-v2-20260713",
    giftAppleBasket2: "assets/items/gift_apple_basket2.png?v=apple-game-ready-v2-20260713",
    harvestBadge: "assets/items/harvest_badge.png?v=apple-game-ready-v2-20260713",
    appleCart: "assets/items/apple_cart.png?v=apple-game-ready-v2-20260713",
    autumnLeaf: "assets/items/autumn_leaf.png",
    roadBranchPile: "assets/props/road_branch_pile.png",
    leafPile: "assets/props/leaf_pile.png",
    roadStonePile: "assets/props/road_stone_pile.png",
    directionSign: "assets/props/direction_sign.png",
    signPiece: "assets/props/sign_piece_pickup.png",
    safeFlag: "assets/props/safe_flag.png",
    trafficLight: "assets/props/traffic_light.png",
    zebraCrossing: "assets/props/zebra_crossing.png",
    forestSchoolDirectionSign: "assets/props/forest_school_direction_sign.png",
    appleValleyMapSign: "assets/props/apple_valley_map_sign.png",
    quizSignMath: "assets/props/quiz_sign_math.png?v=quiz-signs-20260713",
    quizSignLogic: "assets/props/quiz_sign_logic.png?v=quiz-signs-20260713",
    quizSignScience: "assets/props/quiz_sign_science.png?v=quiz-signs-20260713",
    quizSignLanguage: "assets/props/quiz_sign_language.png?v=quiz-signs-20260713",
    quizSignEnglish: "assets/props/quiz_sign_english.png?v=quiz-signs-20260713",
    quizSignRiddle: "assets/props/quiz_sign_riddle.png?v=quiz-signs-20260713",
  };

  const registry = {
    npc: {
      lily: "./assets/asset-pack-01/npc/lily.png",
      coco: "./assets/npc/coco_squirrel.png",
      nono: "./assets/npc/nono_hedgehog.png",
      dodo: "./assets/asset-pack-01/npc/dodo.png",
      ruru: "./assets/npc/ruru_raccoon.png",
      deer: "./assets/asset-pack-01/npc/deer.png",
      ant: "./assets/asset-pack-01/npc/ant.png",
      butterfly: "./assets/asset-pack-01/npc/butterfly.png",
      fox: "./assets/asset-pack-01/npc/fox.png",
      firefly: "./assets/asset-pack-01/npc/firefly.png",
      owlPrincipal: "./assets/npc/owl_principal.png",
      birdPostman: "./assets/npc/bird_postman.png",
      moleFarmer: "./assets/npc/mole_farmer.png",
      otterPostman: "./assets/npc/otter_postman.png",
      frogTeacher: "./assets/npc/frog_teacher.png",
      seagullScout: "./assets/npc/seagull_scout.png",
      beaverEngineer: "./assets/npc/beaver_engineer.png",
      clownfishTwins: "./assets/npc/clownfish_twins.png",
      jellyfishLady: "./assets/npc/jellyfish_lady.png",
      nessieBoss: "./assets/npc/nessie_boss.png",
      fireflyGuide: "./assets/npc/firefly_guide.png",
      littleFrog: "./assets/npc/little_frog.png",
      mudMonster: "./assets/npc/mud_monster.png",
      seaTurtle: "./assets/npc/sea_turtle.png",
      octopusDoctor: "./assets/npc/octopus_doctor.png",
      seahorseGuard: "./assets/npc/seahorse_guard.png",
      lanternFish: "./assets/npc/lantern_fish.png",
    },
    boss: {
      blackBear: "./assets/asset-pack-01/boss/black-bear/idle.png",
    },
    props: {
      apple: "./assets/asset-pack-01/props/apple.png",
      book: "./assets/asset-pack-01/props/guard-book.png",
      guardBook: "./assets/asset-pack-01/props/guard-book.png",
      courageStar: "./assets/asset-pack-01/props/courage-star.png",
      potion: "./assets/asset-pack-01/props/potion.png",
      leafBroom: window.ART_ASSETS.props.leafBroom,
      flowerSeeds: window.ART_ASSETS.props.flowerSeeds,
      pencil: window.ART_ASSETS.props.pencil,
      bell: window.ART_ASSETS.props.bell,
      leafLamp: window.ART_ASSETS.props.leafLamp,
      hangingLantern: window.ART_ASSETS.props.hangingLantern,
      map: window.ART_ASSETS.props.map,
      treasureChest: window.ART_ASSETS.props.treasureChest,
      magicPencil: window.ART_ASSETS.props.magicPencil,
      flowerBulbLamp: window.ART_ASSETS.props.flowerBulbLamp,
      flowerBed: window.ART_ASSETS.props.flowerBed,
      treeStringLights: window.ART_ASSETS.props.treeStringLights,
      antLeaf: window.ART_ASSETS.props.antLeaf,
      antStick: window.ART_ASSETS.props.antStick,
      antFlower: window.ART_ASSETS.props.antFlower,
      puddle: window.ART_ASSETS.props.puddle,
      lampPost: window.ART_ASSETS.props.lampPost,
      lantern: window.ART_ASSETS.props.lantern,
      schoolSign: window.ART_ASSETS.props.schoolSign,
      bouncingMushroom: window.ART_ASSETS.props.bouncingMushroom,
      finishFlag: window.ART_ASSETS.props.finishFlag,
      moonPillar: window.ART_ASSETS.props.moonPillar,
      bubbleSlide: window.ART_ASSETS.props.bubbleSlide,
      pearlSwitch: window.ART_ASSETS.props.pearlSwitch,
      moonLamp: window.ART_ASSETS.props.moonLamp,
      boatPaddle: window.ART_ASSETS.props.boatPaddle,
      moonKey: window.ART_ASSETS.props.moonKey,
      shellBadge: window.ART_ASSETS.props.shellBadge,
      bubbleDivingHelmet: window.ART_ASSETS.props.bubbleDivingHelmet,
      bubbleStone: window.ART_ASSETS.props.bubbleStone,
      pearlOrb: window.ART_ASSETS.props.pearlOrb,
      coralKey: window.ART_ASSETS.props.coralKey,
      spiralShell: window.ART_ASSETS.props.spiralShell,
      seaweedScissors: window.ART_ASSETS.props.seaweedScissors,
      jellyfishCore: window.ART_ASSETS.props.jellyfishCore,
      aquaGem: window.ART_ASSETS.props.aquaGem,
      deepRune: window.ART_ASSETS.props.deepRune,
      moonPearl: window.ART_ASSETS.props.moonPearl,
      pearlCrown: window.ART_ASSETS.props.pearlCrown,
      redApple: window.ART_ASSETS.props.redApple,
      greenApple: window.ART_ASSETS.props.greenApple,
      goldenApple: window.ART_ASSETS.props.goldenApple,
      appleBasket: window.ART_ASSETS.props.appleBasket,
      giftAppleBasket: window.ART_ASSETS.props.giftAppleBasket,
      redAppleBasket: window.ART_ASSETS.props.redAppleBasket,
      greenAppleBasket: window.ART_ASSETS.props.greenAppleBasket,
      giftAppleBasket2: window.ART_ASSETS.props.giftAppleBasket2,
      harvestBadge: window.ART_ASSETS.props.harvestBadge,
      appleCart: window.ART_ASSETS.props.appleCart,
      autumnLeaf: window.ART_ASSETS.props.autumnLeaf,
      roadBranchPile: window.ART_ASSETS.props.roadBranchPile,
      leafPile: window.ART_ASSETS.props.leafPile,
      roadStonePile: window.ART_ASSETS.props.roadStonePile,
      directionSign: window.ART_ASSETS.props.directionSign,
      signPiece: window.ART_ASSETS.props.signPiece,
      safeFlag: window.ART_ASSETS.props.safeFlag,
      trafficLight: window.ART_ASSETS.props.trafficLight,
      zebraCrossing: window.ART_ASSETS.props.zebraCrossing,
      forestSchoolDirectionSign: window.ART_ASSETS.props.forestSchoolDirectionSign,
      appleValleyMapSign: window.ART_ASSETS.props.appleValleyMapSign,
      quizSignMath: window.ART_ASSETS.props.quizSignMath,
      quizSignLogic: window.ART_ASSETS.props.quizSignLogic,
      quizSignScience: window.ART_ASSETS.props.quizSignScience,
      quizSignLanguage: window.ART_ASSETS.props.quizSignLanguage,
      quizSignEnglish: window.ART_ASSETS.props.quizSignEnglish,
      quizSignRiddle: window.ART_ASSETS.props.quizSignRiddle,
    },
    obstacles: {
      pond: "./assets/asset-pack-01/obstacles/pond.png",
      bush: "./assets/asset-pack-01/obstacles/bush.png",
      pit: "./assets/asset-pack-01/obstacles/pit.png",
      stump: "./assets/asset-pack-01/obstacles/stump.png",
      rock: "./assets/asset-pack-01/obstacles/rock.png",
      moonPillar: "./assets/props/moon_pillar.png",
      pearlSwitch: "./assets/props/pearl_switch.png",
      whirlpool: "./assets/effects/whirlpool.png",
      appleTree: "./assets/props/apple_tree.png?v=apple-game-ready-v2-20260713",
    },
    effects: {
      darkBubble: "./assets/effects/dark_bubble.png",
      moonlightCurrent: "./assets/effects/moonlight_current.png",
    },
  };

  const images = {};

  function preload(category, key, src) {
    const image = new Image();
    image.decoding = "async";
    image.src = src;
    images[`${category}:${key}`] = image;
  }

  Object.entries(registry).forEach(([category, entries]) => {
    Object.entries(entries).forEach(([key, src]) => preload(category, key, src));
  });

  window.CATS_OWLS_ART_PACK_01 = {
    get(category, key) {
      if (!window.ENABLE_ART_PACK_01) return null;
      return images[`${category}:${key}`] || null;
    },
    registry,
  };

  document.documentElement.dataset.artPack01 = "ready";
})();
